Repository rohitjmathew/rohitjmathew.space, pull requests merged in 2023-03, with the labels that each got.

#219 Update website with latest details
  components/Container.js
  components/Footer.js
  data/books.mdx
  data/links.mdx
  data/podcasts.mdx
  data/uses.mdx
  lib/mdx.js
  package.json
  pages/about.js
  pages/index.js
  yarn.lock
Labels: 🔍 Ready for Review, size/XXL

#220 Package Updates
  components/Footer.js
  package.json
  pages/about.js
  pages/api/top-tracks.js
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#230 Remove preact from production build
  next.config.js
  package.json
  yarn.lock
Labels: ✅ Approved, size/XXL
